### PR TITLE
Bug 1001343 - Telephony test: add test case of dialing a call from STK

### PR DESCRIPTION
**Pull request by driftersprt**
To support tests with a call dialed from STK, I make the emulator able to dial calls by a new console command.

### CODE REVIEW

**Comment by EdgarChen** [comment]
Since we want to simulate setup call from STK, how about adding new console command under __stk__ category, instead of under __gsm__, e.g. ```stk setupcall <phonenumber>```?

**Comment by driftersprt** [comment]
Thanks for your advice, I totally agree it more suitable to create a new category and put this console command into it, but I think it's more straightforward to name this command as ```stk dial <phonenumber>```, since all this command trying to do is to dial an MO call from the stk. How do you think about this naming?

**Comment by EdgarChen** [comment]
In fact, we have __stk__ category already. :)
Dialing a call from STK is a feature of stk proactive command called __setup call__ [1], so I would like to use the naming aligned with the spec.
Thank you.

[1] Please see [3GPP TS 102.223](http://www.etsi.org/deliver/etsi_ts/102200_102299/102223/12.02.00_60/ts_102223v120200p.pdf), clause 6.4.13.

**Comment by driftersprt** [comment]
Thanks for the information, and the code is updated. :)

**Pull request merged**
